### ISSUE TITLE
View filled in forms for people in care

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#44]
**Prototype**
https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid---Stam-Acasa?node-id=1383%3A3793

**Design**
<img width="241" alt="Screen Shot 2020-04-09 at 2 10 15 PM" src="https://user-images.githubusercontent.com/11520795/78889186-ddd47880-7a6b-11ea-888c-117bf2b35dbf.png">

**Comment by chedydy** [comment]
rezervat.

**Comment by surdu** [comment]
This might be blocked by https://github.com/code4romania/taskforce-fe-components/issues/31

**Comment by surdu** [comment]
@RaduCStefanescu @overeha Is the screenshot mentioned in this issue still valid? I see the design for this page has changed: https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid---Stam-Acasa?node-id=13%3A389

**Comment by RaduCStefanescu** [comment]
@surdu @chedydy we changed the layout for this feature, the last figma you pasted is the way the component will look like
And yes, we are blocked by code4romania/taskforce-fe-components#31

**Comment by surdu** [comment]
@RaduCStefanescu Arguably, we're not blocked by https://github.com/code4romania/taskforce-fe-components/issues/31 anymore, considering we'll need to implement a new component for this.

@RaduCStefanescu @overeha Is there a similar component to this one used in another project so that it warrants a place in the `taskforce-fe-components` or should we implement it directly in this project?

**Comment by RaduCStefanescu** [comment]
Yes, we are still blocked by this and we have a PR that needs to be accepted: https://github.com/code4romania/taskforce-fe-components/pull/128

**Comment by maloun96** [comment]
pot sa-l iau eu?

**Comment by surdu** [comment]
Considering we haven't herd from @chedydy in 12 days, I believe is safe for @maloun96 to take this
