### ISSUE TITLE
Use a common EmailSender service in both StamAcasa.IdentityServer and StamAcasa.EmailService

### ISSUE THREAD

**Issue by trupci** [code4romania/stam-acasa#86]
Right now we have a `SmtpSender` class in `StamAcasa.EmailService` and a `EmailSenderSmtp` class in `StamAcasa.IdentityServer`. Both of them are responsible for sending mails via a `SmtpClient`. 
We should extract this as a common service in `StamAcasa.Common`.

**Comment by cristianMardare** [comment]
The two implementations use different Smtp clients:
- `StamAcasa.IdentityServer.EmailSenderSmtp` uses the [System.Net.Mail version](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netcore-3.1), which seems to be deprecated: 
"We don't recommend that you use the SmtpClient class for new development because SmtpClient doesn't support many modern protocols. Use [MailKit ](https://github.com/jstedfast/MailKit)or other libraries instead. "
- `StamAcasa.EmailService.SmtpSender` uses the version in the [MailKit](https://github.com/jstedfast/MailKit) library

I recommend that the extracted version would also use the MailKit [SmtpClient](http://www.mimekit.net/docs/html/T_MailKit_Net_Smtp_SmtpClient.htm)

**Comment by RaduCStefanescu** [comment]
This issue already has a PR so moving to `In progress`
